apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: storm-tracker
  name: storm-tracker
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/storm-tracker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: storm-tracker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: storm-tracker
    spec:
      containers:
      - image: us.icr.io/living-on-the-cloud/storm-tracker:0.0.2-SNAPSHOT
        imagePullPolicy: Always
        name: storm-tracker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        args: ["--spring.datasource.username=$(db-username)","--spring.datasource.password=$(db-password)"]
        env:
        - name: db-username
          valueFrom:
            secretKeyRef:
              name: db2-connection-info
              key: username
        - name: db-password
          valueFrom:
            secretKeyRef:
              name: db2-connection-info
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30